warehouse_profiles:
  target: bq
  outputs:
    bq:
      type: bigquery
      #method: service-account
      method: oauth
      project: hakoona-matata-298704
      dataset: dataengineering
      threads: 4
      location: US
      priority: interactive
      timeout_seconds: 300
      #keyfile: ./keys/bq.json