version: 2

sources:
  - name: bigquery
    database: hakoona-matata-298704. # project_name
    schema: dataengineering.         # dataset_name
    tables:                          # List of tables in raw layer
      - name: my_first_dbt_model